name: Checkmarx Sarif Integration

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '18 2 * * 5'

permissions:
  security-events: write  # Allow the workflow to upload SARIF files
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step to check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step to run the Checkmarx scan
      - name: Checkmarx scan
        id: checkmarx
        uses: checkmarx/ast-github-action@main
        with:
          base_uri: https://deu.iam.checkmarx.net/
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          cx_tenant: ${{ secrets.CX_TENANT }} # This should be replaced by users' tenant name

      # Step to create a JSON output file from the scan results
      - name: Create JSON output
        run: |
          # Extract scan summary and format it as JSON
          echo '{
            "scan_summary": {
              "vulnerabilities": "${{ steps.checkmarx.outputs.vulnerabilities }}",
              "total": "${{ steps.checkmarx.outputs.total }}",
              "high": "${{ steps.checkmarx.outputs.high }}",
              "medium": "${{ steps.checkmarx.outputs.medium }}",
              "low": "${{ steps.checkmarx.outputs.low }}"
            }
          }' > checkmarx_scan_summary.json

      # Step to upload the JSON summary as an artifact
      - name: Upload JSON summary
        uses: actions/upload-artifact@v3
        with:
          name: checkmarx-scan-summary
          path: checkmarx_scan_summary.json
